insert into flowlet.m_subcategory (
    category_id,
    subcategory_name,
    display_order,
    is_active
)
select category.category_id,
       seed.subcategory_name,
       seed.display_order,
       seed.is_active
from (
    values
        ('給与', 'INCOME', '基本給', 10, true),
        ('給与', 'INCOME', '残業代', 20, true),
        ('給与', 'INCOME', '休日手当', 30, true),
        ('給与', 'INCOME', '通勤手当', 40, true),
        ('給与', 'INCOME', '住宅手当', 50, true),
        ('給与', 'INCOME', 'その他手当', 60, true),
        ('賞与', 'INCOME', '夏季賞与', 10, true),
        ('賞与', 'INCOME', '冬季賞与', 20, true),
        ('賞与', 'INCOME', '決算賞与', 30, true),
        ('一時収入', 'INCOME', '祝い金', 10, true),
        ('一時収入', 'INCOME', 'お小遣い', 20, true),
        ('一時収入', 'INCOME', '給付金', 30, true),
        ('一時収入', 'INCOME', '保険金受取', 40, true),
        ('事業収入', 'INCOME', '売上', 10, true),
        ('事業収入', 'INCOME', '業務委託', 20, true),
        ('事業収入', 'INCOME', '印税', 30, true),
        ('副業収入', 'INCOME', 'アルバイト', 10, true),
        ('副業収入', 'INCOME', 'フリーランス', 20, true),
        ('副業収入', 'INCOME', '広告収入', 30, true),
        ('年金', 'INCOME', '老齢年金', 10, true),
        ('年金', 'INCOME', '企業年金', 20, true),
        ('配当所得', 'INCOME', '国内株配当', 10, true),
        ('配当所得', 'INCOME', '投資信託分配金', 20, true),
        ('配当所得', 'INCOME', 'ETF分配金', 30, true),
        ('利息所得', 'INCOME', '普通預金利息', 10, true),
        ('利息所得', 'INCOME', '定期預金利息', 20, true),
        ('利息所得', 'INCOME', '債券利息', 30, true),
        ('ポイント還元', 'INCOME', 'クレジットカード還元', 10, true),
        ('ポイント還元', 'INCOME', '電子マネー還元', 20, true),
        ('ポイント還元', 'INCOME', 'キャンペーン還元', 30, true),
        ('立替精算', 'INCOME', '社内立替精算', 10, true),
        ('立替精算', 'INCOME', '友人立替精算', 20, true),
        ('還付・返金', 'INCOME', '税金還付', 10, true),
        ('還付・返金', 'INCOME', '商品返金', 20, true),
        ('還付・返金', 'INCOME', '手数料返金', 30, true),
        ('売却収入', 'INCOME', '不用品売却', 10, true),
        ('売却収入', 'INCOME', '資産売却', 20, true),
        ('食費', 'EXPENSE', '食料品', 10, true),
        ('食費', 'EXPENSE', 'コンビニ', 20, true),
        ('食費', 'EXPENSE', '外食', 30, true),
        ('食費', 'EXPENSE', 'カフェ', 40, true),
        ('食費', 'EXPENSE', 'デリバリー', 50, true),
        ('食費', 'EXPENSE', '酒類', 60, true),
        ('日用品', 'EXPENSE', '日用雑貨', 10, true),
        ('日用品', 'EXPENSE', '消耗品', 20, true),
        ('日用品', 'EXPENSE', '家具・家電', 30, true),
        ('日用品', 'EXPENSE', 'ペット用品', 40, true),
        ('住居', 'EXPENSE', '家賃', 10, true),
        ('住居', 'EXPENSE', '住宅ローン', 20, true),
        ('住居', 'EXPENSE', '管理費・修繕積立', 30, true),
        ('住居', 'EXPENSE', '引っ越し', 40, true),
        ('水道光熱', 'EXPENSE', '電気', 10, true),
        ('水道光熱', 'EXPENSE', 'ガス', 20, true),
        ('水道光熱', 'EXPENSE', '水道', 30, true),
        ('水道光熱', 'EXPENSE', '灯油', 40, true),
        ('通信', 'EXPENSE', '携帯電話', 10, true),
        ('通信', 'EXPENSE', '固定回線', 20, true),
        ('通信', 'EXPENSE', '端末代', 30, true),
        ('通信', 'EXPENSE', '郵便・配送', 40, true),
        ('交通', 'EXPENSE', '電車', 10, true),
        ('交通', 'EXPENSE', 'バス', 20, true),
        ('交通', 'EXPENSE', 'タクシー', 30, true),
        ('交通', 'EXPENSE', '航空券', 40, true),
        ('交通', 'EXPENSE', '新幹線', 50, true),
        ('自動車', 'EXPENSE', 'ガソリン', 10, true),
        ('自動車', 'EXPENSE', '駐車場', 20, true),
        ('自動車', 'EXPENSE', '高速料金', 30, true),
        ('自動車', 'EXPENSE', '自動車保険', 40, true),
        ('自動車', 'EXPENSE', '車検・整備', 50, true),
        ('社会保険・税金', 'EXPENSE', '所得税', 10, true),
        ('社会保険・税金', 'EXPENSE', '住民税', 20, true),
        ('社会保険・税金', 'EXPENSE', '国民年金', 30, true),
        ('社会保険・税金', 'EXPENSE', '国民健康保険', 40, true),
        ('社会保険・税金', 'EXPENSE', '固定資産税', 50, true),
        ('保険', 'EXPENSE', '生命保険', 10, true),
        ('保険', 'EXPENSE', '医療保険', 20, true),
        ('保険', 'EXPENSE', '火災保険', 30, true),
        ('保険', 'EXPENSE', '地震保険', 40, true),
        ('医療', 'EXPENSE', '診療', 10, true),
        ('医療', 'EXPENSE', '薬', 20, true),
        ('医療', 'EXPENSE', '歯科', 30, true),
        ('医療', 'EXPENSE', '検診', 40, true),
        ('教育', 'EXPENSE', '学費', 10, true),
        ('教育', 'EXPENSE', '教材', 20, true),
        ('教育', 'EXPENSE', '習い事', 30, true),
        ('教育', 'EXPENSE', '資格受験料', 40, true),
        ('仕事', 'EXPENSE', '書籍', 10, true),
        ('仕事', 'EXPENSE', '備品', 20, true),
        ('仕事', 'EXPENSE', 'ソフトウェア', 30, true),
        ('仕事', 'EXPENSE', '会議・接待', 40, true),
        ('衣服・美容', 'EXPENSE', '衣服', 10, true),
        ('衣服・美容', 'EXPENSE', 'クリーニング', 20, true),
        ('衣服・美容', 'EXPENSE', '美容院', 30, true),
        ('衣服・美容', 'EXPENSE', '化粧品', 40, true),
        ('交際', 'EXPENSE', '交際費', 10, true),
        ('交際', 'EXPENSE', '贈答', 20, true),
        ('交際', 'EXPENSE', '冠婚葬祭', 30, true),
        ('娯楽', 'EXPENSE', '映画・動画', 10, true),
        ('娯楽', 'EXPENSE', 'ゲーム', 20, true),
        ('娯楽', 'EXPENSE', 'イベント', 30, true),
        ('娯楽', 'EXPENSE', '趣味用品', 40, true),
        ('サブスク', 'EXPENSE', '動画配信', 10, true),
        ('サブスク', 'EXPENSE', '音楽配信', 20, true),
        ('サブスク', 'EXPENSE', 'クラウドサービス', 30, true),
        ('サブスク', 'EXPENSE', '会員費', 40, true),
        ('旅行', 'EXPENSE', '宿泊', 10, true),
        ('旅行', 'EXPENSE', '観光', 20, true),
        ('旅行', 'EXPENSE', '旅行保険', 30, true),
        ('旅行', 'EXPENSE', '旅行雑費', 40, true),
        ('特別支出', 'EXPENSE', '家電購入', 10, true),
        ('特別支出', 'EXPENSE', '家具購入', 20, true),
        ('特別支出', 'EXPENSE', '冠婚葬祭', 30, true),
        ('特別支出', 'EXPENSE', '寄付', 40, true),
        ('その他支出', 'EXPENSE', '雑費', 10, true),
        ('その他支出', 'EXPENSE', '手数料', 20, true),
        ('その他支出', 'EXPENSE', '未分類', 30, true),
        ('口座間移動', 'TRANSFER', '普通預金間移動', 10, true),
        ('口座間移動', 'TRANSFER', '目的別口座振替', 20, true),
        ('口座間移動', 'TRANSFER', '家族口座移動', 30, true),
        ('口座間移動', 'TRANSFER', '先取り貯金', 40, true),
        ('口座間移動', 'TRANSFER', '貯蓄口座へ移動', 50, true),
        ('口座間移動', 'TRANSFER', '生活防衛資金へ移動', 60, true),
        ('口座間移動', 'TRANSFER', '目的別積立へ移動', 70, true),
        ('カード引落', 'TRANSFER', 'クレジットカード支払い', 10, true),
        ('カード引落', 'TRANSFER', 'デビットカード引落', 20, true),
        ('カード引落', 'TRANSFER', '口座振替支払い', 30, true),
        ('電子マネー移動', 'TRANSFER', '電子マネーチャージ', 10, true),
        ('電子マネー移動', 'TRANSFER', '電子マネー払戻', 20, true),
        ('電子マネー移動', 'TRANSFER', 'QR決済チャージ', 30, true),
        ('証券口座移動', 'TRANSFER', '証券口座入金', 10, true),
        ('証券口座移動', 'TRANSFER', '証券口座出金', 20, true),
        ('証券口座移動', 'TRANSFER', 'NISA積立振替', 30, true),
        ('現金引き出し', 'TRANSFER', 'ATM引き出し', 10, true),
        ('現金引き出し', 'TRANSFER', 'レジ引き出し', 20, true),
        ('現金預け入れ', 'TRANSFER', 'ATM預け入れ', 10, true),
        ('現金預け入れ', 'TRANSFER', 'レジ入金', 20, true),
        ('振替調整', 'TRANSFER', '残高調整', 10, true),
        ('振替調整', 'TRANSFER', '誤登録修正', 20, true)
) as seed(category_name, category_type, subcategory_name, display_order, is_active)
join flowlet.m_category category
    on category.category_name = seed.category_name
   and category.category_type = seed.category_type
where not exists (
    select 1
    from flowlet.m_subcategory existing
    where existing.category_id = category.category_id
      and existing.subcategory_name = seed.subcategory_name
);
