spring:
  datasource:
    url: jdbc:postgresql://localhost:${FLOWLET_DB_DEV_PORT:5432}/${FLOWLET_DB_DEV_NAME:flowlet_dev}
    username: ${FLOWLET_DB_DEV_USER:flowlet}
    password: ${FLOWLET_DB_DEV_PASSWORD:flowlet}
