spring:
  application:
    name: flowlet
  jackson:
    time-zone: Asia/Tokyo
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${FLOWLET_DB_SCHEMA:flowlet}
        jdbc:
          time_zone: Asia/Tokyo
  flyway:
    enabled: true
    default-schema: ${FLOWLET_DB_SCHEMA:flowlet}
    schemas: ${FLOWLET_DB_SCHEMA:flowlet}
